packages:
  - apps/*
  - packages/*
  - scripts/*

catalog:
  zod: ^3.25.42
  better-auth: ^1.3.4
  autumn-js: ^0.0.48
  superjson: ^2.2.2
  '@trpc/server': ^11.1.4
  '@trpc/client': ^11.1.4
  '@trpc/tanstack-react-query': ^11.1.4
  wrangler: ^4.28.1
  typescript: ^5.8.3
  drizzle-orm: ^0.43.1
  drizzle-kit: ^0.31.1
  '@types/node': ^22.15.21
  react: ^19.1.0
  react-dom: ^19.1.0

onlyBuiltDependencies:
  - '@sentry/cli'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - core-js
  - core-js-pure
  - esbuild
  - msw
  - sharp
  - unrs-resolver
  - workerd

patchedDependencies:
  novel: patches/novel.patch
